on:
  push:
    branches: [ staging ]
name: Build Staging
jobs:
  deploy-staging:
    name: "Deploy Staging"
    uses: ./.github/workflows/build.yml
    with:
      environment: staging
    secrets: inherit